

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Data {
                ref class CollectionViewSource;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class TextBlock;
                ref class Button;
                ref class ListView;
                ref class ItemsControl;
                ref class GridView;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualStateGroup;
            ref class VisualState;
        }
    }
}

namespace MyFirstApp
{
    partial ref class SearchPeople : public ::MyFirstApp::Common::LayoutAwarePage, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Data::CollectionViewSource^ resultsViewSource;
        private: ::Windows::UI::Xaml::Data::CollectionViewSource^ filtersViewSource;
        private: ::Windows::UI::Xaml::Controls::Grid^ resultsPanel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ noResultsTextBlock;
        private: ::Windows::UI::Xaml::Controls::Button^ backButton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pageTitle;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ resultText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ queryText;
        private: ::Windows::UI::Xaml::Controls::Grid^ typicalPanel;
        private: ::Windows::UI::Xaml::Controls::Grid^ snappedPanel;
        private: ::Windows::UI::Xaml::Controls::ListView^ resultsListView;
        private: ::Windows::UI::Xaml::Controls::ItemsControl^ filtersItemsControl;
        private: ::Windows::UI::Xaml::Controls::GridView^ resultsGridView;
        private: ::Windows::UI::Xaml::VisualStateGroup^ ApplicationViewStates;
        private: ::Windows::UI::Xaml::VisualStateGroup^ ResultStates;
        private: ::Windows::UI::Xaml::VisualState^ ResultsFound;
        private: ::Windows::UI::Xaml::VisualState^ NoResultsFound;
        private: ::Windows::UI::Xaml::VisualState^ FullScreenLandscape;
        private: ::Windows::UI::Xaml::VisualState^ Filled;
        private: ::Windows::UI::Xaml::VisualState^ FullScreenPortrait;
        private: ::Windows::UI::Xaml::VisualState^ Snapped;
    };
}

